// A public class to hold data for constant string values
public with sharing class GlobalConstants {
    public static final String INVESTING_FUND_BASE_URL = 'https://www.investing.com/funds/';
    public static final String INVESTING_FUND_MATCHING_TEXT = '<span class="arial_26 inlineblock pid-';

    public static final String YAHOO_STOCK_BASE_URL = 'https://query1.finance.yahoo.com/v8/finance/chart/';
    public static final String YAHOO_STOCK_INTERVAL_1DAY = '?interval=1d';

    public static final String HTTP_GET = 'GET';
    public static final String HTTP_POST = 'POST';

    public static final String GlobalConstants.BOND = 'Bond';
    public static final String GlobalConstants.EPF = 'EPF';
    public static final String GlobalConstants.FD = 'FD';
    public static final String GlobalConstants.MF = 'MF';
    public static final String GlobalConstants.METAL = 'Metal';
    public static final String GlobalConstants.PPF = 'PPF';
    public static final String GlobalConstants.SIP = 'SIP';
    public static final String GlobalConstants.SMALLCASE = 'SmallCase';
    public static final String GlobalConstants.STOCK = 'Stock';
    public static final String GlobalConstants.TREASURYBILL = 'TreasuryBill';
    public static final String GlobalConstants.ULIP = 'ULIP';
    public static final String GlobalConstants.NPS = 'NPS';
    public static final String GlobalConstants.NONE = 'None';
}